name = "ACEAX NIArms Compat"
prefix = "aceax_niarms_compat"
mainprefix = "z"
[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "README.md",
    "LICENSE",
    "logo_niarms_co.paa", # Change to propper file name
]

[version]
path = "addons/main/mod_macros.hpp"
git_hash = 0

[hemtt.launch]
workshop = [
    # Will not auto download on workshop you must do so manually
    "450814997",  # CBA_A3
    "463939057",  # ACE
    "2522638637", # ACEAX

    # NIARMS
    "667454606",  # CORE
    # "1091513876", # P226
    # "875779698",  # ACR-E
    # "774809509",  # MG3
    # "592647598",  # SG510
    # "2883704439", # SCAR
    # "509714345",  # Minimi
    # "330924923",  # MP5
    # "667386534",  # M14
    # "594378620",  # G36
    # "667375637",  # G3
    # "410126510",  # FAL

    # Added this update
    # "509730197",  # AWM
    # "637519731",  # AUG
    # "667396202",  # AR15
    # "667352839",  # AK
    # "1266202915", # FN30-11 Rifles
    # "1729907725" # C96 Pistols


    # Yet to add
    # "2594443368",  # M1941 Johnson LMG
]
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching",
]
