name = "ACEAX NIArms Compat"
prefix = "aceax_niarms_compat"
mainprefix = "z"
[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "README.md",
    "LICENSE",
    "logo_niarms_ca.paa", # Change to propper file name
]

[version]
path = "addons/main/mod_macros.hpp"
git_hash = 0

[hemtt.launch]
workshop = [
    # Will not auto download on workshop you must do so manually
    "450814997",  # CBA_A3
    "463939057",  # ACE
    "2522638637",  # ACEAX

    "667454606" #NIArms CORE
]
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching",
]
