name = "ACEAX NIArms Compat"
prefix = "aceax_niarms_compat"
mainprefix = "z"
[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "README.md",
    "LICENSE",
    "logo_niarms_co.paa", # Change to propper file name
]

[version]
path = "addons/main/mod_macros.hpp"
git_hash = 0

[hemtt.launch]
workshop = [
    # Will not auto download on workshop you must do so manually
    "450814997",  # CBA_A3
    "463939057",  # ACE
    "2522638637",  # ACEAX

    "667454606", #NIArms CORE
    "875779698", #NIArms ACR-E
    "667386534", #NiArms M14
    "774809509",  #NIArms MG3
    "509714345",  # NIArms Minimi
    "330924923", #NIArms MP5
    "1091513876",  # NIArms P226
    "2883704439", #NIArms SCAR
    "592647598",  # NIArms SG510
]
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching",
]
