name = "NIArms SCAR ACEAX Compat"
prefix = "niarmsscar_aceax_compat"
mainprefix = "z"


[version]
path = "addons/main/mod_macros.hpp"
git_hash = 4


[hemtt.launch]
workshop = [
    "450814997",  #CBA_A3
    "463939057",  #ACE
    "2522638637", #ACEAX

    "667454606", #NIArms CORE
    "2883704439", #NIArms SCAR
]
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching",
]
