name = " ACEAX NIArms SCAR Compat"
prefix = "niarmsscar_aceax_compat"
mainprefix = "z"
[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "README.md",
    "LICENSE",
    "logo_niscar_ca.paa", # Change to propper file name
]

[version]
path = "addons/main/mod_macros.hpp"
git_hash = 0


[hemtt.launch]
workshop = [
    "450814997",  #CBA_A3
    "463939057",  #ACE
    "2522638637", #ACEAX

    "667454606", #NIArms CORE
    "2883704439", #NIArms SCAR
]
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching",
]
