name = "ACEAX NIArms ACR-E Compat"
prefix = "niarmsacr_aceax_compat"
mainprefix = "z"
[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "README.md",
    "LICENSE",
    "logo_niacr_ca.paa", # Change to propper file name
]

[version]
path = "addons/main/mod_macros.hpp"
git_hash = 0

[hemtt.launch]
workshop = [
    "450814997",  #CBA_A3
    "463939057",  #ACE
    "2522638637", #ACEAX

    "667454606", #NIArms CORE
    "875779698", #NIArms ACR-E
]
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching",
]
